spring.application.name=togyebu

#database
spring.datasource.url=jdbc:mysql://localhost:3306/togyebu
spring.datasource.username=jehyun
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

#devtools auto load
spring.devtools.restart.enabled=true
